<?php
/**
* Ifthenpay_MbWay module dependency
*
* @category    Gateway Payment
* @package     Ifthenpay_MbWay
* @author      Ifthenpay
* @copyright   Ifthenpay (http://www.ifthenpay.com)
* @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
*/

if ($block->isMethodIfthenpay()) { ?>
    <div id="checkout.ifthenpay_mb_way.success">
        <table style="width: auto;min-width: 280px;max-width: 320px;padding: 5px;font-size: 11px;color: #374953;border: 1px solid #dddddd; margin-top: 30px;margin-bottom: 40px;">
            <tbody>
                <tr>
                    <td style="padding: 5px;" colspan="2">
                        <div align="left">
                            <img src="https://ifthenpay.com/img/mbway.png" alt="mbway">
                        </div>
                    </td>
                </tr>
                <tr>
                    <td align="left" style=" padding:10px; font-weight:bold; text-align:left">Telemovel:</td>
                    <td align="left" style=" padding:10px; text-align:left"><?php echo $block->getData('phone_number'); ?></td>
                </tr>
                <tr>
                    <td align="left" style=" padding:10px; padding-top:10px; font-weight:bold; text-align:left">Encomenda:</td>
                    <td align="left" style=" padding:10px; padding-top:10px; text-align:left"><?php echo $block->getData('order_id'); ?></td>
                </tr>
                <tr>
                    <td align="left" style="padding:10px; padding-bottom:15px; padding-top:10px; font-weight:bold; text-align:left">Valor:</td>
                    <td style="padding:10px; padding-bottom:15px; padding-top:10px; text-align:left"><?php echo $block->getData('grand_total'); ?>€</td>
                </tr>
                    <tr>
                        <td style="font-size: x-small; padding:0; border: 0px; text-align:center;" colspan="2">Por favor verifique na App MBWAY e proceda ao pagamento da sua encomenda. <br>Processado por <a href="https://www.ifthenpay.com" target="_blanck">Ifthenpay</a>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
<?php } ?>

